import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import { DataGoogleApi, ytVideo } from '../@types/types'
import SimpleCard from '../components/assets/SimpleCard'
import Menu from '../components/Header/menu/Menu'

type IProps = {
  dataYT: DataGoogleApi
}

const Home = (props: IProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main>
        <section>
          {props.dataYT?.items
            .filter(tem => tem.id.kind === 'youtube#video')
            .map((vid: ytVideo) => (
              <SimpleCard key={`${vid.etag}${vid.id.videoId}`} {...vid} />
            ))}
        </section>
      </main>

      <footer>
          Powered by{' '}
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { NEXT_PUBLIC_API_LOCAL } = process.env
  const { dataYT } = await fetch(NEXT_PUBLIC_API_LOCAL || 'http://localhost:3000/api/cast').then(res =>
    res.json()
  )

  return {
    props: {
      title: 'Home',
      dataYT
    }
  }
}
